# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFairypresent', '0002_auto_20170809_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Subscriber', 'verbose_name_plural': 'A lot of Subscribers'},
        ),
    ]
