# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=None, upload_to='products_images/'),
        ),
    ]
